@extends('layouts.app')

@section('title', __('overtime.admin_title'))
@section('page-title', __('overtime.admin_title'))

@section('content')
    @if ($errors->any())<x-alert variant="danger" :title="__('ui.design.error_title')" class="mb-6"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-alert>@endif
    <section class="rounded-3xl bg-navy-950 px-6 py-9 text-white shadow-panel sm:px-9"><p class="text-xs font-bold uppercase tracking-[.2em] text-brand-400">{{ __('overtime.eyebrow') }}</p><h1 class="mt-3 text-3xl font-bold">{{ __('overtime.admin_title') }}</h1><p class="mt-3 max-w-3xl text-sm leading-6 text-slate-300">{{ __('overtime.admin_description') }}</p></section>
    @unless($canManage)<x-alert variant="info" :title="__('overtime.read_only')" class="mt-6">{{ __('overtime.read_only_help') }}</x-alert>@endunless

    <section class="surface-panel mt-6 rounded-2xl border p-6 shadow-panel"><h2 class="text-xl font-bold text-primary">{{ __('overtime.rules') }}</h2><div class="mt-5 overflow-x-auto"><table class="min-w-full text-left text-sm"><thead><tr><th class="py-2">{{ __('overtime.legal_entity') }}</th><th>{{ __('overtime.code') }}</th><th>{{ __('overtime.day_type') }}</th><th>{{ __('overtime.calculation_method') }}</th><th>{{ __('overtime.minimum_minutes') }}</th><th>{{ __('overtime.maximum_minutes') }}</th><th>{{ __('overtime.effective_from') }}</th></tr></thead><tbody class="divide-y divide-slate-200 dark:divide-slate-800">@forelse($rules as $rule)<tr><td class="py-3">{{ $rule->legalEntity?->code }}</td><td>{{ $rule->code }}</td><td>{{ __('overtime.day_types.'.$rule->day_type->value) }}</td><td>{{ __('overtime.methods.'.$rule->calculation_method) }}</td><td>{{ $rule->minimum_minutes }}</td><td>{{ $rule->maximum_minutes }}</td><td>{{ $rule->effective_from?->format('d M Y') }}</td></tr>@empty<tr><td colspan="7" class="py-5 text-secondary">{{ __('overtime.no_records') }}</td></tr>@endforelse</tbody></table></div></section>

    @if($canManage)
        <section class="mt-6 grid gap-6 xl:grid-cols-2">
            <article class="surface-panel rounded-2xl border p-6 shadow-panel"><h2 class="text-xl font-bold text-primary">{{ __('overtime.create_rule') }}</h2><form method="POST" action="{{ route('overtime.admin.rules.store') }}" class="mt-5 grid gap-4 sm:grid-cols-2">@csrf
                <x-form.select name="legal_entity_public_id" :label="__('overtime.legal_entity')" required>@foreach($entities as $entity)<option value="{{ $entity->public_id }}">{{ $entity->display_name }}</option>@endforeach</x-form.select>
                <x-form.input name="code" :label="__('overtime.code')" required /><x-form.input name="name" :label="__('overtime.name')" required />
                <x-form.select name="day_type" :label="__('overtime.day_type')">@foreach(__('overtime.day_types') as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</x-form.select>
                <x-form.select name="calculation_method" :label="__('overtime.calculation_method')">@foreach(__('overtime.methods') as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</x-form.select>
                <x-form.input name="minimum_minutes" type="number" min="0" :label="__('overtime.minimum_minutes')" required /><x-form.input name="maximum_minutes" type="number" min="1" :label="__('overtime.maximum_minutes')" required />
                <x-form.input name="rounding_increment_minutes" type="number" min="1" :label="__('overtime.rounding_increment')" required />
                <x-form.select name="rounding_mode" :label="__('overtime.rounding_mode')">@foreach(__('overtime.rounding_modes') as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</x-form.select>
                <div class="sm:col-span-2"><label for="segment_rules_json" class="block text-sm font-bold text-primary">{{ __('overtime.segment_rules') }}</label><textarea id="segment_rules_json" name="segment_rules_json" rows="4" class="control mt-2" placeholder='[{"up_to_minutes":60,"multiplier_hundredths":150},{"up_to_minutes":null,"multiplier_hundredths":200}]' required>{{ old('segment_rules_json') }}</textarea><p class="mt-2 text-xs text-secondary">{{ __('overtime.segment_rules_help') }}</p></div>
                <x-form.input name="meal_threshold_minutes" type="number" min="1" :label="__('overtime.meal_threshold')" /><x-form.input name="meal_allowance_idr" type="number" min="0" :label="__('overtime.meal_amount')" />
                <x-form.input name="transport_threshold_minutes" type="number" min="1" :label="__('overtime.transport_threshold')" /><x-form.input name="transport_allowance_idr" type="number" min="0" :label="__('overtime.transport_amount')" />
                <x-form.select name="eligibility" :label="__('overtime.eligibility')">@foreach(__('overtime.eligibilities') as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</x-form.select>
                <x-form.input name="effective_from" type="date" :label="__('overtime.effective_from')" required /><x-form.input name="effective_to" type="date" :label="__('overtime.effective_to')" />
                <div class="sm:col-span-2"><x-button type="submit">{{ __('overtime.create_rule') }}</x-button></div>
            </form></article>

            <article class="surface-panel rounded-2xl border p-6 shadow-panel"><h2 class="text-xl font-bold text-primary">{{ __('overtime.delegation') }}</h2><form method="POST" action="{{ route('overtime.admin.delegations.store') }}" class="mt-5 grid gap-4 sm:grid-cols-2">@csrf
                <x-form.select name="legal_entity_public_id" :label="__('overtime.legal_entity')">@foreach($entities as $entity)<option value="{{ $entity->public_id }}">{{ $entity->display_name }}</option>@endforeach</x-form.select>
                <x-form.select name="delegator_user_id" :label="__('overtime.delegator')">@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</x-form.select>
                <x-form.select name="delegate_user_id" :label="__('overtime.delegate')">@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</x-form.select>
                <x-form.input name="reason" :label="__('overtime.reason')" required /><x-form.input name="effective_from" type="date" :label="__('overtime.effective_from')" required /><x-form.input name="effective_to" type="date" :label="__('overtime.effective_to')" required />
                <div class="sm:col-span-2"><x-button type="submit">{{ __('overtime.delegation') }}</x-button></div>
            </form><div class="mt-5 space-y-2">@foreach($delegations as $delegation)<div class="flex items-center justify-between gap-3 rounded-xl border p-3 text-sm dark:border-slate-800"><span>{{ $delegation->delegate?->name }} · {{ $delegation->effective_from?->format('d M') }}—{{ $delegation->effective_to?->format('d M Y') }} · {{ $delegation->status }}</span>@if($delegation->status === 'active')<form method="POST" action="{{ route('overtime.admin.delegations.revoke', $delegation) }}">@csrf @method('PUT')<x-button type="submit" variant="danger">{{ __('overtime.revoke') }}</x-button></form>@endif</div>@endforeach</div></article>
        </section>
    @endif

    <section class="surface-panel mt-6 rounded-2xl border p-6 shadow-panel"><div class="flex flex-wrap items-end justify-between gap-4"><div><h2 class="text-xl font-bold text-primary">{{ __('overtime.report') }}</h2><p class="mt-2 text-sm text-secondary">{{ __('overtime.report_help') }}</p></div>@if($canExport)<form method="GET" action="{{ route('overtime.admin.report.export') }}" class="flex flex-wrap items-end gap-3"><x-form.input name="from" type="date" :label="__('overtime.work_date')" /><x-form.input name="to" type="date" :label="__('overtime.effective_to')" /><x-button type="submit">{{ __('overtime.export_csv') }}</x-button></form>@endif</div><div class="mt-5 overflow-x-auto"><table class="min-w-full text-left text-sm"><thead><tr><th class="py-2">{{ __('overtime.employee') }}</th><th>{{ __('overtime.work_date') }}</th><th>{{ __('overtime.planned_minutes') }}</th><th>{{ __('overtime.approved_minutes') }}</th><th>{{ __('overtime.actual_minutes') }}</th><th>{{ __('overtime.payable_minutes') }}</th><th>Status</th></tr></thead><tbody class="divide-y divide-slate-200 dark:divide-slate-800">@forelse($requests as $overtimeRequest)<tr><td class="py-3">{{ $overtimeRequest->employee?->full_name }}</td><td>{{ $overtimeRequest->work_date?->format('d M Y') }}</td><td>{{ $overtimeRequest->planned_minutes }}</td><td>{{ $overtimeRequest->approved_minutes ?? '—' }}</td><td>{{ $overtimeRequest->actual_minutes ?? '—' }}</td><td>{{ $overtimeRequest->payable_minutes ?? '—' }}</td><td>{{ __('overtime.statuses.'.$overtimeRequest->requestStatus()->value) }}</td></tr>@empty<tr><td colspan="7" class="py-5 text-secondary">{{ __('overtime.no_records') }}</td></tr>@endforelse</tbody></table></div></section>
@endsection
